apiVersion: v2
name: docling
description: Docling document processing service for Kubernetes
type: application
version: 0.0.1
appVersion: "0.16.0"
home: https://github.com/docling-project/docling
sources:
  - https://github.com/docling-project/docling
  - https://quay.io/repository/docling-project/docling-serve
keywords:
  - document
  - processing
  - pdf
  - extraction
  - ai
annotations:
  licenses: MIT