{{/*
Configuration for Docling
*/}}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "docling.fullname" . }}-config
  namespace: {{ include "docling.namespace" . }}
  labels:
    {{- include "docling.labels" . | nindent 4 }}
data:
  DOCLING_SERVE_ENABLE_UI: {{ .Values.config.enableUI | quote }}
  {{- range $key, $value := .Values.config.extraEnv }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}

---
{{- if .Values.storage.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "docling.fullname" . }}-storage
  namespace: {{ include "docling.namespace" . }}
  labels:
    {{- include "docling.labels" . | nindent 4 }}
spec:
  accessModes: [ReadWriteOnce]
  {{- if .Values.storage.storageClass }}
  storageClassName: {{ .Values.storage.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
{{- end }}