# Default values for colibo-docs-extractor
image:
  repository: itkdev/colibo-docs-extrator
  tag: latest
  pullPolicy: IfNotPresent

schedule: "0 * * * *"  # Run every hour by default

args: ["sync"]

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

volumes:
  syncDb:
    enabled: true
    path: /app/database
    # Use PVC for persistent storage
    persistentVolumeClaim:
      enabled: true
      existingClaim: ""
      storageClassName: ""
      size: 10Mi

app:
  databaseUrl: "sqlite:///database/sync.db"
  colibo:
    url: ''
    rootDocIid: ''
    scope: 'api Documents.ReadWrite.All'
    client:
      # Use existing secret and keys in that secret
      existingSecret: ''
      idKey: ''
      secretKey: ''
      # If not using secret.
      id: ''
      secret: ''
  webui:
    url: ''
    client:
      # Use existing secret and keys in that secret
      existingSecret: ''
      tokenKey: ''
      knowledgeKey: ''
      # If not using secret.
      token: ''
      knowledgeId: ''

env: []
# - name: EXAMPLE_VAR
#   value: "example-value"
# - name: SECRET_VAR
#   valueFrom:
#     secretKeyRef:
#       name: my-secret
#       key: secret-key

# If you need to pull image from private registry
imagePullSecrets: []
# - name: regcred

podAnnotations: {}

nodeSelector: {}

tolerations: []

affinity: {}