apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "searxng.fullname" . }}-config
  labels:
    {{- include "searxng.labels" . | nindent 4 }}
data:
  settings.yml: |
{{ tpl (.Files.Get "files/settings.yml") . | indent 4 }}