name: Check Colibo Helm Charts

on:
  pull_request:
    paths:
      - "charts/colibo-docs-extrator/**"
  push:
    paths:
      - "charts/colibo-docs-extrator/**"

jobs:
  lint-chart:
    name: Lint Helm Chart
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Lint colibo-docs-extrator Helm Chart
        run: |
          helm lint ./charts/colibo-docs-extrator

  test-deploy:
    name: Test Chart Deployment
    runs-on: ubuntu-latest
    needs: lint-chart

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Set up KinD Cluster
        uses: helm/kind-action@v1

      - name: Template Colibo Helm Chart
        run: |
          helm template colibo-docs-extrator ./charts/colibo-docs-extrator \
            --namespace test-namespace --create-namespace > template.yaml

      - name: Verify Colibo
        run: |
          kubectl create namespace test-namespace
          kubectl apply --namespace test-namespace -f template.yaml
